apiVersion: apps/v1
kind: Deployment
metadata:
  name: vind-box-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vind-box-operator
  template:
    metadata:
      labels:
        app: vind-box-operator
    spec:
      serviceAccountName: vind-box-operator
      containers:
      - name: manager
        image: vind-box-operator:v0.0.2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vind-box-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vind-box-operator-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # MVP over-privilege
subjects:
- kind: ServiceAccount
  name: vind-box-operator
  namespace: default
