spin_manifest_version = 2

[application]
name = "api"
version = "0.1.0"
authors = ["yebyen"]
description = "Vind-Box Cloud Gateway"

[[trigger.http]]
route = "/..."
component = "api"

[component.api]
source = "target/wasm32-wasip1/release/api.wasm"
allowed_outbound_hosts = ["https://kubernetes.default.svc"]
[component.api.variables]
k8s_token = "{{ k8s_token }}"

[component.api.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
