apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vind-box
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/yebyen/useless # Assuming this is the repo URL
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vind-box-operator
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/apps/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: vind-box
  targetNamespace: default
