apiVersion: v1
kind: Service
metadata:
  name: vind-box-api-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    core.spinkube.dev/app-name: vind-box-api
