apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: vind-box-api
  namespace: default
spec:
  image: "ttl.sh/vind-box-api:final-v6"
  replicas: 1
  serviceAccountName: vind-box-api
  executor: containerd-shim-spin
  variables:
    - name: k8s_token
      valueFrom:
        secretKeyRef:
          name: vind-box-api-token
          key: token
    - name: k8s_api_url
      value: "http://proxy-service.default.svc:8001"
    - name: SSL_CERT_FILE
      value: "/etc/ssl/certs/ca-certificates.crt"
